import os

# OUTPUT_DIR = "paper_output"
OUTPUT_DIR = "paper_output_extra"
OUTPUT_CONVERT_DIR = "paper_output_convert"
ITEM_AU_ADDR_FILE_NAME = "item_au_addr.txt"
ITEM_TITLE_FILE_NAME = "item_title.txt"
ITEM_ABSTRACT_FILE_NAME = "item_abstract.txt"
ITEM_GRANT_FILE_NAME = "item_grant.txt"
ITEM_JOURNAL_FILE_NAME = "item_journal.txt"
ITEM_KEYWORD_FILE_NAME = "item_keyword.txt"
ITEM_KEYWORD_WIDE_FILE_NAME = "item_keyword_wide.txt"
ITEM_EMAIL_FILE_NAME = "item_email.txt"
ITEM_AFFILIATION_FILE_NAME = "item_affiliation.txt"
ITEM_FIELD_FILE_NAME = "item_field.txt"
ITEM_COUNTRY_FILE_NAME = "item_country.txt"
ITEM_JOURNAL_REF_FILE_NAME = "journal_ref.txt"
ITEM_PATENT_REF_FILE_NAME = "patent_ref.txt"
ITEM_BOOK_REF_FILE_NAME = "book_ref.txt"
ITEM_FILE_NAME = "item.txt"
ITEM_AUTHOR_FILE_NAME = "item_author.txt"
RP_AUTHORS_FILE_NAME = "rp_authors.txt"
ITEM_FIELD2_FILE_NAME = "item_field2.txt"
OUTPUT_FILE_SEPARATOR = "|_"
PROC_HISTORY_UTS_FILE_NAME = ITEM_FILE_NAME


class FilePathDef:
    ITEM_AU_ADDR_FILE_PATH = os.path.join(OUTPUT_DIR, ITEM_AU_ADDR_FILE_NAME)
    ITEM_AUTHOR_FILE_PATH = os.path.join(OUTPUT_DIR, ITEM_AUTHOR_FILE_NAME)
    ITEM_TITLE_FILE_PATH = os.path.join(OUTPUT_DIR, ITEM_TITLE_FILE_NAME)
    ITEM_ABSTRACT_FILE_PATH = os.path.join(OUTPUT_DIR, ITEM_ABSTRACT_FILE_NAME)
    ITEM_GRANT_FILE_PATH = os.path.join(OUTPUT_DIR, ITEM_GRANT_FILE_NAME)
    ITEM_JOURNAL_FILE_PATH = os.path.join(OUTPUT_DIR, ITEM_JOURNAL_FILE_NAME)
    ITEM_KEYWORD_FILE_PATH = os.path.join(OUTPUT_DIR, ITEM_KEYWORD_FILE_NAME)
    ITEM_KEYWORD_WIDE_FILE_PATH = os.path.join(OUTPUT_DIR, ITEM_KEYWORD_WIDE_FILE_NAME)
    ITEM_EMAIL_FILE_PATH = os.path.join(OUTPUT_DIR, ITEM_EMAIL_FILE_NAME)
    ITEM_AFFILIATION_FILE_PATH = os.path.join(OUTPUT_DIR, ITEM_AFFILIATION_FILE_NAME)
    ITEM_FIELD_FILE_PATH = os.path.join(OUTPUT_DIR, ITEM_FIELD_FILE_NAME)
    ITEM_FIELD2_FILE_PATH = os.path.join(OUTPUT_DIR, ITEM_FIELD2_FILE_NAME)
    ITEM_COUNTRY_FILE_PATH = os.path.join(OUTPUT_DIR, ITEM_COUNTRY_FILE_NAME)
    ITEM_JOURNAL_REF_FILE_PATH = os.path.join(OUTPUT_DIR, ITEM_JOURNAL_REF_FILE_NAME)
    ITEM_PATENT_REF_FILE_PATH = os.path.join(OUTPUT_DIR, ITEM_PATENT_REF_FILE_NAME)
    ITEM_BOOK_REF_FILE_PATH = os.path.join(OUTPUT_DIR, ITEM_BOOK_REF_FILE_NAME)
    ITEM_FILE_PATH = os.path.join(OUTPUT_DIR, ITEM_FILE_NAME)
    RP_AUTHORS_FILE_PATH = os.path.join(OUTPUT_DIR, RP_AUTHORS_FILE_NAME)
    PROC_HISTORY_UTS_FILE_PATH = os.path.join(OUTPUT_DIR, PROC_HISTORY_UTS_FILE_NAME)
