#!/usr/bin/env python3
"""
MySQL/MariaDB Database Import Script for WOS XML Parser Output

This script imports CSV files generated by the WOS XML Parser into a MySQL or MariaDB database.
It creates the database schema and imports all 33 CSV files into their respective tables.

Requirements:
    - MySQL or MariaDB server running and accessible
    - pymysql package (install with: pip install pymysql)
    - Note: Works with both MySQL and MariaDB servers
    
Usage:
    python import_to_mysql.py [--host HOST] [--user USER] [--password PASSWORD] 
                              [--database DATABASE] [--csv-dir CSV_DIR]
                              [--drop-existing]
                              
Examples:
    # Basic usage with defaults
    python import_to_mysql.py
    
    # Specify custom database and credentials
    python import_to_mysql.py --host localhost --user root --password mypass --database wos_xml
    
    # Drop and recreate existing database (WARNING: this deletes all data)
    python import_to_mysql.py --drop-existing
"""

import csv
import os
import sys
import argparse
from datetime import datetime

# Try to import the MySQL/MariaDB library
try:
    import pymysql
    DB_LIBRARY = 'pymysql'
except ImportError:
    try:
        import MySQLdb as pymysql
        from MySQLdb import cursors as pymysql_cursors
        # Create compatibility wrapper for mysqlclient
        pymysql.cursors = pymysql_cursors
        DB_LIBRARY = 'mysqlclient'
    except ImportError:
        print("Error: No MySQL/MariaDB library found!")
        print("Please install one of the following:")
        print("  - PyMySQL: pip install pymysql")
        print("  - mysqlclient: pip install mysqlclient")
        sys.exit(1)


# Database configuration defaults
DEFAULT_CONFIG = {
    'host': 'localhost',
    'user': 'root',
    'password': '',
    'database': 'wos_xml',
    'charset': 'utf8mb4',
    'csv_dir': 'xml_output'
}


# Table creation SQL statements based on tables.md schema
TABLE_SCHEMAS = {
    # Section 1: Paper Basic Information Tables
    'item': """
        CREATE TABLE IF NOT EXISTS item (
            uid VARCHAR(50) PRIMARY KEY,
            sortdate DATE,
            pubyear SMALLINT,
            has_abstract CHAR(1),
            vol VARCHAR(50),
            issue VARCHAR(50),
            part VARCHAR(50),
            supplement VARCHAR(200),
            special_issue VARCHAR(200),
            early_access_date VARCHAR(50),
            early_access_month VARCHAR(50),
            early_access_year VARCHAR(50),
            page_begin VARCHAR(20),
            page_end VARCHAR(20),
            page_count VARCHAR(20),
            INDEX idx_pubyear (pubyear),
            INDEX idx_sortdate (sortdate)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    'item_title': """
        CREATE TABLE IF NOT EXISTS item_title (
            uid VARCHAR(50),
            title TEXT,
            PRIMARY KEY (uid),
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    'item_abstract': """
        CREATE TABLE IF NOT EXISTS item_abstract (
            uid VARCHAR(50),
            abstract TEXT,
            PRIMARY KEY (uid),
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE,
            FULLTEXT INDEX idx_abstract (abstract)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    'item_doc_types': """
        CREATE TABLE IF NOT EXISTS item_doc_types (
            id INT AUTO_INCREMENT PRIMARY KEY,
            uid VARCHAR(50),
            doctype VARCHAR(100),
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE,
            INDEX idx_uid (uid),
            INDEX idx_doctype (doctype)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    'item_doc_types_norm': """
        CREATE TABLE IF NOT EXISTS item_doc_types_norm (
            id INT AUTO_INCREMENT PRIMARY KEY,
            uid VARCHAR(50),
            doctype_norm VARCHAR(100),
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE,
            INDEX idx_uid (uid),
            INDEX idx_doctype_norm (doctype_norm)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    'item_langs': """
        CREATE TABLE IF NOT EXISTS item_langs (
            id INT AUTO_INCREMENT PRIMARY KEY,
            uid VARCHAR(50),
            type VARCHAR(50),
            language VARCHAR(100),
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE,
            INDEX idx_uid (uid),
            INDEX idx_language (language)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    'item_langs_norm': """
        CREATE TABLE IF NOT EXISTS item_langs_norm (
            id INT AUTO_INCREMENT PRIMARY KEY,
            uid VARCHAR(50),
            type VARCHAR(50),
            language_norm VARCHAR(100),
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE,
            INDEX idx_uid (uid),
            INDEX idx_language_norm (language_norm)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    'item_editions': """
        CREATE TABLE IF NOT EXISTS item_editions (
            id INT AUTO_INCREMENT PRIMARY KEY,
            uid VARCHAR(50),
            edition VARCHAR(50),
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE,
            INDEX idx_uid (uid),
            INDEX idx_edition (edition)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    'item_keywords': """
        CREATE TABLE IF NOT EXISTS item_keywords (
            id INT AUTO_INCREMENT PRIMARY KEY,
            uid VARCHAR(50),
            keyword VARCHAR(500),
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE,
            INDEX idx_uid (uid),
            INDEX idx_keyword (keyword(255))
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    'item_keywords_plus': """
        CREATE TABLE IF NOT EXISTS item_keywords_plus (
            id INT AUTO_INCREMENT PRIMARY KEY,
            uid VARCHAR(50),
            keyword_plus VARCHAR(500),
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE,
            INDEX idx_uid (uid),
            INDEX idx_keyword_plus (keyword_plus(255))
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    'item_source': """
        CREATE TABLE IF NOT EXISTS item_source (
            uid VARCHAR(50) PRIMARY KEY,
            source VARCHAR(500),
            source_abbrev VARCHAR(200),
            abbrev_iso VARCHAR(200),
            abbrev_11 VARCHAR(50),
            abbrev_29 VARCHAR(100),
            series VARCHAR(500),
            book_subtitle TEXT,
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE,
            INDEX idx_source (source(255))
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    'item_ids': """
        CREATE TABLE IF NOT EXISTS item_ids (
            id INT AUTO_INCREMENT PRIMARY KEY,
            uid VARCHAR(50),
            identifier_type VARCHAR(50),
            identifier_value VARCHAR(200),
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE,
            INDEX idx_uid (uid),
            INDEX idx_identifier_type (identifier_type),
            INDEX idx_identifier_value (identifier_value)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    'item_oas': """
        CREATE TABLE IF NOT EXISTS item_oas (
            id INT AUTO_INCREMENT PRIMARY KEY,
            uid VARCHAR(50),
            oa_type VARCHAR(100),
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE,
            INDEX idx_uid (uid),
            INDEX idx_oa_type (oa_type)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    'item_publishers': """
        CREATE TABLE IF NOT EXISTS item_publishers (
            id INT AUTO_INCREMENT PRIMARY KEY,
            uid VARCHAR(50),
            addr_no VARCHAR(50),
            full_address TEXT,
            city VARCHAR(200),
            role VARCHAR(100),
            seq_no VARCHAR(50),
            display_name VARCHAR(500),
            full_name VARCHAR(500),
            unified_name VARCHAR(500),
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE,
            INDEX idx_uid (uid)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    # Section 2: Author Information Tables
    'item_authors': """
        CREATE TABLE IF NOT EXISTS item_authors (
            id INT AUTO_INCREMENT PRIMARY KEY,
            uid VARCHAR(50),
            seq_no VARCHAR(50),
            role VARCHAR(50),
            reprint CHAR(1),
            display_name VARCHAR(500),
            wos_standard VARCHAR(500),
            full_name VARCHAR(500),
            first_name VARCHAR(200),
            last_name VARCHAR(200),
            suffix VARCHAR(50),
            email_addr VARCHAR(200),
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE,
            INDEX idx_uid (uid),
            INDEX idx_full_name (full_name(255)),
            INDEX idx_last_name (last_name)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    'item_addresses': """
        CREATE TABLE IF NOT EXISTS item_addresses (
            id INT AUTO_INCREMENT PRIMARY KEY,
            uid VARCHAR(50),
            addr_no VARCHAR(50),
            full_address TEXT,
            city VARCHAR(200),
            state VARCHAR(200),
            country VARCHAR(200),
            zip VARCHAR(50),
            zip_location VARCHAR(200),
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE,
            INDEX idx_uid (uid),
            INDEX idx_country (country),
            INDEX idx_city (city)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    'item_au_addrs': """
        CREATE TABLE IF NOT EXISTS item_au_addrs (
            id INT AUTO_INCREMENT PRIMARY KEY,
            uid VARCHAR(50),
            seq_no VARCHAR(50),
            address_no VARCHAR(50),
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE,
            INDEX idx_uid (uid),
            INDEX idx_seq_no (seq_no)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    'item_addr_aus': """
        CREATE TABLE IF NOT EXISTS item_addr_aus (
            id INT AUTO_INCREMENT PRIMARY KEY,
            uid VARCHAR(50),
            seq_no VARCHAR(50),
            address_no VARCHAR(50),
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE,
            INDEX idx_uid (uid),
            INDEX idx_seq_no (seq_no)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    'item_orgs': """
        CREATE TABLE IF NOT EXISTS item_orgs (
            id INT AUTO_INCREMENT PRIMARY KEY,
            uid VARCHAR(50),
            addr_no VARCHAR(50),
            org_pref VARCHAR(50),
            ROR_ID VARCHAR(100),
            org_id VARCHAR(100),
            organization VARCHAR(1000),
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE,
            INDEX idx_uid (uid),
            INDEX idx_organization (organization(255))
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    'item_suborgs': """
        CREATE TABLE IF NOT EXISTS item_suborgs (
            id INT AUTO_INCREMENT PRIMARY KEY,
            uid VARCHAR(50),
            addr_no VARCHAR(50),
            suborganization VARCHAR(1000),
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE,
            INDEX idx_uid (uid),
            INDEX idx_suborganization (suborganization(255))
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    'item_author_ids': """
        CREATE TABLE IF NOT EXISTS item_author_ids (
            id INT AUTO_INCREMENT PRIMARY KEY,
            uid VARCHAR(50),
            seq_no VARCHAR(50),
            r_id VARCHAR(100),
            orcid VARCHAR(100),
            orcid_tr VARCHAR(100),
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE,
            INDEX idx_uid (uid),
            INDEX idx_orcid (orcid)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    'item_rp_addrs': """
        CREATE TABLE IF NOT EXISTS item_rp_addrs (
            id INT AUTO_INCREMENT PRIMARY KEY,
            uid VARCHAR(50),
            addr_no VARCHAR(50),
            full_address TEXT,
            city VARCHAR(200),
            state VARCHAR(200),
            country VARCHAR(200),
            zip VARCHAR(50),
            zip_location VARCHAR(200),
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE,
            INDEX idx_uid (uid),
            INDEX idx_country (country)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    'item_rp_au_addrs': """
        CREATE TABLE IF NOT EXISTS item_rp_au_addrs (
            id INT AUTO_INCREMENT PRIMARY KEY,
            uid VARCHAR(50),
            seq_no VARCHAR(50),
            address_no VARCHAR(50),
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE,
            INDEX idx_uid (uid)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    'item_rp_orgs': """
        CREATE TABLE IF NOT EXISTS item_rp_orgs (
            id INT AUTO_INCREMENT PRIMARY KEY,
            uid VARCHAR(50),
            addr_no VARCHAR(50),
            org_pref VARCHAR(50),
            ROR_ID VARCHAR(100),
            org_id VARCHAR(100),
            organization VARCHAR(1000),
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE,
            INDEX idx_uid (uid),
            INDEX idx_organization (organization(255))
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    'item_rp_suborgs': """
        CREATE TABLE IF NOT EXISTS item_rp_suborgs (
            id INT AUTO_INCREMENT PRIMARY KEY,
            uid VARCHAR(50),
            addr_no VARCHAR(50),
            suborganization VARCHAR(1000),
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE,
            INDEX idx_uid (uid)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    'item_contributors': """
        CREATE TABLE IF NOT EXISTS item_contributors (
            id INT AUTO_INCREMENT PRIMARY KEY,
            uid VARCHAR(50),
            seq_no VARCHAR(50),
            orcid_id VARCHAR(100),
            r_id VARCHAR(100),
            r_id_role VARCHAR(100),
            display_name VARCHAR(500),
            full_name VARCHAR(500),
            first_name VARCHAR(200),
            last_name VARCHAR(200),
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE,
            INDEX idx_uid (uid),
            INDEX idx_orcid_id (orcid_id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    # Section 3: Category Tables
    'item_headings': """
        CREATE TABLE IF NOT EXISTS item_headings (
            id INT AUTO_INCREMENT PRIMARY KEY,
            uid VARCHAR(50),
            headings VARCHAR(500),
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE,
            INDEX idx_uid (uid),
            INDEX idx_headings (headings(255))
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    'item_subjects': """
        CREATE TABLE IF NOT EXISTS item_subjects (
            id INT AUTO_INCREMENT PRIMARY KEY,
            uid VARCHAR(50),
            subject VARCHAR(500),
            ascatype VARCHAR(50),
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE,
            INDEX idx_uid (uid),
            INDEX idx_subject (subject(255))
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    # Section 4: References Tables
    'item_references': """
        CREATE TABLE IF NOT EXISTS item_references (
            id INT AUTO_INCREMENT PRIMARY KEY,
            uid VARCHAR(50),
            occurence_order VARCHAR(50),
            cited_uid VARCHAR(50),
            cited_author VARCHAR(500),
            cited_year VARCHAR(50),
            cited_page VARCHAR(100),
            cited_volume VARCHAR(100),
            cited_title TEXT,
            cited_work VARCHAR(1000),
            cited_doi VARCHAR(200),
            cited_assignee VARCHAR(500),
            patent_no VARCHAR(200),
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE,
            INDEX idx_uid (uid),
            INDEX idx_cited_uid (cited_uid)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    'item_cite_locations': """
        CREATE TABLE IF NOT EXISTS item_cite_locations (
            id INT AUTO_INCREMENT PRIMARY KEY,
            uid VARCHAR(50),
            occurence_order VARCHAR(50),
            physical_location VARCHAR(200),
            section VARCHAR(200),
            function VARCHAR(200),
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE,
            INDEX idx_uid (uid)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    # Section 5: Funding Information Tables
    'item_acks': """
        CREATE TABLE IF NOT EXISTS item_acks (
            uid VARCHAR(50) PRIMARY KEY,
            ack_text TEXT,
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE,
            FULLTEXT INDEX idx_ack_text (ack_text)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    'item_grants': """
        CREATE TABLE IF NOT EXISTS item_grants (
            id INT AUTO_INCREMENT PRIMARY KEY,
            uid VARCHAR(50),
            grant_agency VARCHAR(1000),
            grant_agency_pref VARCHAR(500),
            grant_id VARCHAR(200),
            grant_source VARCHAR(100),
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE,
            INDEX idx_uid (uid),
            INDEX idx_grant_agency (grant_agency(255))
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """,
    
    # Section 6: Conference Information Table
    'item_conferences': """
        CREATE TABLE IF NOT EXISTS item_conferences (
            id INT AUTO_INCREMENT PRIMARY KEY,
            uid VARCHAR(50),
            conf_id VARCHAR(100),
            conf_info TEXT,
            conf_title VARCHAR(1000),
            conf_start VARCHAR(50),
            conf_end VARCHAR(50),
            conf_date VARCHAR(200),
            conf_city VARCHAR(200),
            conf_state VARCHAR(200),
            sponsor TEXT,
            FOREIGN KEY (uid) REFERENCES item(uid) ON DELETE CASCADE,
            INDEX idx_uid (uid),
            INDEX idx_conf_id (conf_id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """
}


# Define the order of table creation (respecting foreign key dependencies)
TABLE_ORDER = [
    # Section 1: Must create item first as it's the parent table
    'item',
    'item_title',
    'item_abstract',
    'item_doc_types',
    'item_doc_types_norm',
    'item_langs',
    'item_langs_norm',
    'item_editions',
    'item_keywords',
    'item_keywords_plus',
    'item_source',
    'item_ids',
    'item_oas',
    'item_publishers',
    # Section 2
    'item_authors',
    'item_addresses',
    'item_au_addrs',
    'item_addr_aus',
    'item_orgs',
    'item_suborgs',
    'item_author_ids',
    'item_rp_addrs',
    'item_rp_au_addrs',
    'item_rp_orgs',
    'item_rp_suborgs',
    'item_contributors',
    # Section 3
    'item_headings',
    'item_subjects',
    # Section 4
    'item_references',
    'item_cite_locations',
    # Section 5
    'item_acks',
    'item_grants',
    # Section 6
    'item_conferences'
]


class MySQLImporter:
    """Handles importing CSV files to MySQL database"""
    
    def __init__(self, config):
        """Initialize importer with database configuration"""
        self.config = config
        self.connection = None
        self.stats = {
            'tables_created': 0,
            'rows_imported': 0,
            'files_processed': 0,
            'errors': []
        }
    
    def connect(self):
        """Establish connection to MySQL/MariaDB server"""
        try:
            # First connect without database to check/create it
            self.connection = pymysql.connect(
                host=self.config['host'],
                user=self.config['user'],
                password=self.config['password'],
                charset=self.config['charset'],
                cursorclass=pymysql.cursors.DictCursor
            )
            
            # Detect database type (MySQL vs MariaDB)
            with self.connection.cursor() as cursor:
                cursor.execute("SELECT VERSION()")
                version = cursor.fetchone()['VERSION()']
                db_type = "MariaDB" if "MariaDB" in version else "MySQL"
                print(f"✓ Connected to {db_type} server at {self.config['host']}")
                print(f"  Server version: {version}")
                print(f"  Using library: {DB_LIBRARY}")
            
            return True
        except pymysql.Error as e:
            print(f"✗ Error connecting to MySQL/MariaDB: {e}")
            self.stats['errors'].append(f"Connection error: {e}")
            return False
    
    def create_database(self, drop_existing=False):
        """Create database if it doesn't exist"""
        try:
            with self.connection.cursor() as cursor:
                if drop_existing:
                    print(f"⚠ Dropping existing database '{self.config['database']}' if it exists...")
                    cursor.execute(f"DROP DATABASE IF EXISTS `{self.config['database']}`")
                
                cursor.execute(f"CREATE DATABASE IF NOT EXISTS `{self.config['database']}` "
                             f"CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci")
                cursor.execute(f"USE `{self.config['database']}`")
                self.connection.commit()
                print(f"✓ Database '{self.config['database']}' is ready")
                return True
        except pymysql.Error as e:
            print(f"✗ Error creating database: {e}")
            self.stats['errors'].append(f"Database creation error: {e}")
            return False
    
    def create_tables(self):
        """Create all tables according to schema"""
        print("\n" + "="*60)
        print("Creating database tables...")
        print("="*60)
        
        try:
            with self.connection.cursor() as cursor:
                # Disable foreign key checks during table creation
                cursor.execute("SET FOREIGN_KEY_CHECKS=0")
                
                for table_name in TABLE_ORDER:
                    if table_name in TABLE_SCHEMAS:
                        try:
                            cursor.execute(TABLE_SCHEMAS[table_name])
                            self.stats['tables_created'] += 1
                            print(f"✓ Created table: {table_name}")
                        except pymysql.Error as e:
                            error_msg = f"Error creating table {table_name}: {e}"
                            print(f"✗ {error_msg}")
                            self.stats['errors'].append(error_msg)
                
                # Re-enable foreign key checks
                cursor.execute("SET FOREIGN_KEY_CHECKS=1")
                self.connection.commit()
                
                print(f"\n✓ Successfully created {self.stats['tables_created']} tables")
                return True
        except pymysql.Error as e:
            print(f"✗ Error in table creation: {e}")
            self.stats['errors'].append(f"Table creation error: {e}")
            return False
    
    def import_csv_file(self, table_name, csv_file_path):
        """Import a single CSV file into its corresponding table"""
        if not os.path.exists(csv_file_path):
            print(f"⚠ CSV file not found: {csv_file_path}, skipping...")
            return 0
        
        try:
            with open(csv_file_path, 'r', encoding='utf-8') as csvfile:
                reader = csv.DictReader(csvfile)
                rows = list(reader)
                
                if not rows:
                    print(f"  ⚠ Empty file: {table_name}.csv")
                    return 0
                
                # Get column names from CSV header
                columns = list(rows[0].keys())
                
                # Prepare INSERT statement
                placeholders = ', '.join(['%s'] * len(columns))
                column_names = ', '.join([f'`{col}`' for col in columns])
                insert_sql = f"INSERT INTO `{table_name}` ({column_names}) VALUES ({placeholders})"
                
                # Batch insert for better performance
                with self.connection.cursor() as cursor:
                    batch_size = 1000
                    total_rows = 0
                    
                    for i in range(0, len(rows), batch_size):
                        batch = rows[i:i + batch_size]
                        batch_data = [
                            tuple(row[col] if row[col] != '' else None for col in columns)
                            for row in batch
                        ]
                        cursor.executemany(insert_sql, batch_data)
                        total_rows += len(batch)
                    
                    self.connection.commit()
                    print(f"  ✓ Imported {total_rows:,} rows into {table_name}")
                    return total_rows
                    
        except pymysql.Error as e:
            error_msg = f"Error importing {table_name}: {e}"
            print(f"  ✗ {error_msg}")
            self.stats['errors'].append(error_msg)
            return 0
        except Exception as e:
            error_msg = f"Unexpected error importing {table_name}: {e}"
            print(f"  ✗ {error_msg}")
            self.stats['errors'].append(error_msg)
            return 0
    
    def import_all_csv_files(self):
        """Import all CSV files from the output directory"""
        print("\n" + "="*60)
        print("Importing CSV files into database...")
        print("="*60)
        
        csv_dir = self.config['csv_dir']
        
        if not os.path.exists(csv_dir):
            print(f"✗ CSV directory not found: {csv_dir}")
            print(f"Please make sure the XML parser has been run and CSV files are generated.")
            return False
        
        start_time = datetime.now()
        
        for table_name in TABLE_ORDER:
            csv_file = os.path.join(csv_dir, f"{table_name}.csv")
            print(f"\nImporting {table_name}.csv...")
            rows_imported = self.import_csv_file(table_name, csv_file)
            self.stats['rows_imported'] += rows_imported
            self.stats['files_processed'] += 1
        
        elapsed_time = (datetime.now() - start_time).total_seconds()
        
        print("\n" + "="*60)
        print("Import Summary")
        print("="*60)
        print(f"Files processed: {self.stats['files_processed']}")
        print(f"Total rows imported: {self.stats['rows_imported']:,}")
        print(f"Time elapsed: {elapsed_time:.2f} seconds")
        
        if self.stats['errors']:
            print(f"\n⚠ {len(self.stats['errors'])} errors occurred:")
            for error in self.stats['errors'][:10]:  # Show first 10 errors
                print(f"  - {error}")
            if len(self.stats['errors']) > 10:
                print(f"  ... and {len(self.stats['errors']) - 10} more errors")
        else:
            print("\n✓ Import completed successfully with no errors!")
        
        return True
    
    def close(self):
        """Close database connection"""
        if self.connection:
            self.connection.close()
            print("\n✓ Database connection closed")


def main():
    """Main entry point for the script"""
    parser = argparse.ArgumentParser(
        description='Import WOS XML Parser CSV output into MySQL database',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s
  %(prog)s --host localhost --user root --password mypass
  %(prog)s --database wos_xml --csv-dir xml_output
  %(prog)s --drop-existing  # WARNING: Deletes existing database
        """
    )
    
    parser.add_argument('--host', default=DEFAULT_CONFIG['host'],
                       help=f"MySQL host (default: {DEFAULT_CONFIG['host']})")
    parser.add_argument('--user', default=DEFAULT_CONFIG['user'],
                       help=f"MySQL user (default: {DEFAULT_CONFIG['user']})")
    parser.add_argument('--password', default=DEFAULT_CONFIG['password'],
                       help="MySQL password (default: empty)")
    parser.add_argument('--database', default=DEFAULT_CONFIG['database'],
                       help=f"Database name (default: {DEFAULT_CONFIG['database']})")
    parser.add_argument('--csv-dir', default=DEFAULT_CONFIG['csv_dir'],
                       help=f"CSV files directory (default: {DEFAULT_CONFIG['csv_dir']})")
    parser.add_argument('--drop-existing', action='store_true',
                       help="Drop existing database before creating (WARNING: deletes all data)")
    
    args = parser.parse_args()
    
    # Build configuration
    config = {
        'host': args.host,
        'user': args.user,
        'password': args.password,
        'database': args.database,
        'charset': DEFAULT_CONFIG['charset'],
        'csv_dir': args.csv_dir
    }
    
    print("="*60)
    print("WOS XML Parser - MySQL/MariaDB Import Tool")
    print("="*60)
    print(f"Host: {config['host']}")
    print(f"User: {config['user']}")
    print(f"Database: {config['database']}")
    print(f"CSV Directory: {config['csv_dir']}")
    print("="*60)
    
    if args.drop_existing:
        print("\n⚠ WARNING: --drop-existing flag is set!")
        print(f"⚠ This will DELETE the existing '{config['database']}' database and all its data!")
        response = input("Are you sure you want to continue? (yes/no): ")
        if response.lower() != 'yes':
            print("Operation cancelled.")
            return 1
    
    # Create importer and run import process
    importer = MySQLImporter(config)
    
    try:
        # Connect to MySQL
        if not importer.connect():
            return 1
        
        # Create database
        if not importer.create_database(drop_existing=args.drop_existing):
            return 1
        
        # Create tables
        if not importer.create_tables():
            return 1
        
        # Import CSV files
        if not importer.import_all_csv_files():
            return 1
        
        print("\n" + "="*60)
        print("✓ All operations completed successfully!")
        print("="*60)
        return 0
        
    except KeyboardInterrupt:
        print("\n\n⚠ Operation cancelled by user")
        return 1
    except Exception as e:
        print(f"\n✗ Unexpected error: {e}")
        import traceback
        traceback.print_exc()
        return 1
    finally:
        importer.close()


if __name__ == '__main__':
    sys.exit(main())
