-- =============================================================================
-- WOS XML Parser - CSV Data Import Script
-- =============================================================================
-- This script imports CSV files generated by the WOS XML Parser into the
-- MySQL or MariaDB database. It must be run after create_database_and_tables.sql.
--
-- Prerequisites:
--   1. Database and tables must be created first (run create_database_and_tables.sql)
--   2. CSV files must be present in the xml_output directory
--   3. MySQL/MariaDB must have FILE privilege and secure_file_priv setting configured
--
-- Usage:
--   mysql -u root -p wos_xml < import_csv_data.sql
--   OR
--   mariadb -u root -p wos_xml < import_csv_data.sql
--
-- Note: This script assumes CSV files are in the xml_output directory.
-- You may need to update the file paths if your CSV files are located elsewhere.
-- =============================================================================

-- Use the database
USE wos_xml;

-- Temporarily disable foreign key checks for faster import
SET FOREIGN_KEY_CHECKS = 0;

-- Set SQL mode for CSV import compatibility
SET SESSION SQL_MODE = '';

-- =============================================================================
-- Section 1: Paper Basic Information Tables (14 tables)
-- Import in order respecting foreign key dependencies
-- =============================================================================

-- Import item table (parent table, must be first)
LOAD DATA LOCAL INFILE 'xml_output/item.csv'
INTO TABLE item
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(uid, @sortdate, @pubyear, @has_abstract, @vol, @issue, @part, @supplement, 
 @special_issue, @early_access_date, @early_access_month, @early_access_year, 
 @page_begin, @page_end, @page_count)
SET
    sortdate = NULLIF(@sortdate, ''),
    pubyear = NULLIF(@pubyear, ''),
    has_abstract = NULLIF(@has_abstract, ''),
    vol = NULLIF(@vol, ''),
    issue = NULLIF(@issue, ''),
    part = NULLIF(@part, ''),
    supplement = NULLIF(@supplement, ''),
    special_issue = NULLIF(@special_issue, ''),
    early_access_date = NULLIF(@early_access_date, ''),
    early_access_month = NULLIF(@early_access_month, ''),
    early_access_year = NULLIF(@early_access_year, ''),
    page_begin = NULLIF(@page_begin, ''),
    page_end = NULLIF(@page_end, ''),
    page_count = NULLIF(@page_count, '');

-- Import item_title
LOAD DATA LOCAL INFILE 'xml_output/item_title.csv'
INTO TABLE item_title
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
ESCAPED BY ''
LINES TERMINATED BY '\r\n'  -- 关键：使用 Windows 行尾
IGNORE 1 LINES
(uid, @title)
SET title = NULLIF(@title, '');

-- Import item_abstract
LOAD DATA LOCAL INFILE 'xml_output/item_abstract.csv'
INTO TABLE item_abstract
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
ESCAPED BY ''
LINES TERMINATED BY '\r\n'  -- 关键：使用 Windows 行尾
IGNORE 1 LINES
(uid, @abstract)
SET abstract = NULLIF(@abstract, '');

-- Import item_doc_types
LOAD DATA LOCAL INFILE 'xml_output/item_doc_types.csv'
INTO TABLE item_doc_types
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@id, uid, @doctype)
SET doctype = NULLIF(@doctype, '');

-- Import item_doc_types_norm
LOAD DATA LOCAL INFILE 'xml_output/item_doc_types_norm.csv'
INTO TABLE item_doc_types_norm
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@id, uid, @doctype_norm)
SET doctype_norm = NULLIF(@doctype_norm, '');

-- Import item_langs
LOAD DATA LOCAL INFILE 'xml_output/item_langs.csv'
INTO TABLE item_langs
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@id, uid, @type, @language)
SET 
    type = NULLIF(@type, ''),
    language = NULLIF(@language, '');

-- Import item_langs_norm
LOAD DATA LOCAL INFILE 'xml_output/item_langs_norm.csv'
INTO TABLE item_langs_norm
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@id, uid, @type, @language_norm)
SET 
    type = NULLIF(@type, ''),
    language_norm = NULLIF(@language_norm, '');

-- Import item_editions
LOAD DATA LOCAL INFILE 'xml_output/item_editions.csv'
INTO TABLE item_editions
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@id, uid, @edition)
SET edition = NULLIF(@edition, '');

-- Import item_keywords
LOAD DATA LOCAL INFILE 'xml_output/item_keywords.csv'
INTO TABLE item_keywords
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@id, uid, @keyword)
SET keyword = NULLIF(@keyword, '');

-- Import item_keywords_plus
LOAD DATA LOCAL INFILE 'xml_output/item_keywords_plus.csv'
INTO TABLE item_keywords_plus
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@id, uid, @keyword_plus)
SET keyword_plus = NULLIF(@keyword_plus, '');

-- Import item_source
LOAD DATA LOCAL INFILE 'xml_output/item_source.csv'
INTO TABLE item_source
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(uid, @source, @source_abbrev, @abbrev_iso, @abbrev_11, @abbrev_29, @series, @book_subtitle)
SET
    source = NULLIF(@source, ''),
    source_abbrev = NULLIF(@source_abbrev, ''),
    abbrev_iso = NULLIF(@abbrev_iso, ''),
    abbrev_11 = NULLIF(@abbrev_11, ''),
    abbrev_29 = NULLIF(@abbrev_29, ''),
    series = NULLIF(@series, ''),
    book_subtitle = NULLIF(@book_subtitle, '');

-- Import item_ids
LOAD DATA LOCAL INFILE 'xml_output/item_ids.csv'
INTO TABLE item_ids
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@id, uid, @identifier_type, @identifier_value)
SET
    identifier_type = NULLIF(@identifier_type, ''),
    identifier_value = NULLIF(@identifier_value, '');

-- Import item_oas
LOAD DATA LOCAL INFILE 'xml_output/item_oas.csv'
INTO TABLE item_oas
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@id, uid, @oa_type)
SET oa_type = NULLIF(@oa_type, '');

-- Import item_publishers
LOAD DATA LOCAL INFILE 'xml_output/item_publishers.csv'
INTO TABLE item_publishers
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@id, uid, @addr_no, @full_address, @city, @role, @seq_no, @display_name, @full_name, @unified_name)
SET
    addr_no = NULLIF(@addr_no, ''),
    full_address = NULLIF(@full_address, ''),
    city = NULLIF(@city, ''),
    role = NULLIF(@role, ''),
    seq_no = NULLIF(@seq_no, ''),
    display_name = NULLIF(@display_name, ''),
    full_name = NULLIF(@full_name, ''),
    unified_name = NULLIF(@unified_name, '');

-- =============================================================================
-- Section 2: Author Information Tables (12 tables)
-- =============================================================================

-- Import item_authors
LOAD DATA LOCAL INFILE 'xml_output/item_authors.csv'
INTO TABLE item_authors
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@id, uid, @seq_no, @role, @reprint, @display_name, @wos_standard, @full_name, 
 @first_name, @last_name, @suffix, @email_addr)
SET
    seq_no = NULLIF(@seq_no, ''),
    role = NULLIF(@role, ''),
    reprint = NULLIF(@reprint, ''),
    display_name = NULLIF(@display_name, ''),
    wos_standard = NULLIF(@wos_standard, ''),
    full_name = NULLIF(@full_name, ''),
    first_name = NULLIF(@first_name, ''),
    last_name = NULLIF(@last_name, ''),
    suffix = NULLIF(@suffix, ''),
    email_addr = NULLIF(@email_addr, '');

-- Import item_addresses
LOAD DATA LOCAL INFILE 'xml_output/item_addresses.csv'
INTO TABLE item_addresses
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@id, uid, @addr_no, @full_address, @city, @state, @country, @zip, @zip_location)
SET
    addr_no = NULLIF(@addr_no, ''),
    full_address = NULLIF(@full_address, ''),
    city = NULLIF(@city, ''),
    state = NULLIF(@state, ''),
    country = NULLIF(@country, ''),
    zip = NULLIF(@zip, ''),
    zip_location = NULLIF(@zip_location, '');

-- Import item_au_addrs
LOAD DATA LOCAL INFILE 'xml_output/item_au_addrs.csv'
INTO TABLE item_au_addrs
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@id, uid, @seq_no, @address_no)
SET
    seq_no = NULLIF(@seq_no, ''),
    address_no = NULLIF(@address_no, '');

-- Import item_addr_aus
LOAD DATA LOCAL INFILE 'xml_output/item_addr_aus.csv'
INTO TABLE item_addr_aus
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@id, uid, @seq_no, @address_no)
SET
    seq_no = NULLIF(@seq_no, ''),
    address_no = NULLIF(@address_no, '');

-- Import item_orgs
LOAD DATA LOCAL INFILE 'xml_output/item_orgs.csv'
INTO TABLE item_orgs
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@id, uid, @addr_no, @org_pref, @ROR_ID, @org_id, @organization)
SET
    addr_no = NULLIF(@addr_no, ''),
    org_pref = NULLIF(@org_pref, ''),
    ROR_ID = NULLIF(@ROR_ID, ''),
    org_id = NULLIF(@org_id, ''),
    organization = NULLIF(@organization, '');

-- Import item_suborgs
LOAD DATA LOCAL INFILE 'xml_output/item_suborgs.csv'
INTO TABLE item_suborgs
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@id, uid, @addr_no, @suborganization)
SET
    addr_no = NULLIF(@addr_no, ''),
    suborganization = NULLIF(@suborganization, '');

-- Import item_author_ids
LOAD DATA LOCAL INFILE 'xml_output/item_author_ids.csv'
INTO TABLE item_author_ids
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@id, uid, @seq_no, @r_id, @orcid, @orcid_tr)
SET
    seq_no = NULLIF(@seq_no, ''),
    r_id = NULLIF(@r_id, ''),
    orcid = NULLIF(@orcid, ''),
    orcid_tr = NULLIF(@orcid_tr, '');

-- Import item_rp_addrs
LOAD DATA LOCAL INFILE 'xml_output/item_rp_addrs.csv'
INTO TABLE item_rp_addrs
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@id, uid, @addr_no, @full_address, @city, @state, @country, @zip, @zip_location)
SET
    addr_no = NULLIF(@addr_no, ''),
    full_address = NULLIF(@full_address, ''),
    city = NULLIF(@city, ''),
    state = NULLIF(@state, ''),
    country = NULLIF(@country, ''),
    zip = NULLIF(@zip, ''),
    zip_location = NULLIF(@zip_location, '');

-- Import item_rp_au_addrs
LOAD DATA LOCAL INFILE 'xml_output/item_rp_au_addrs.csv'
INTO TABLE item_rp_au_addrs
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@id, uid, @seq_no, @address_no)
SET
    seq_no = NULLIF(@seq_no, ''),
    address_no = NULLIF(@address_no, '');

-- Import item_rp_orgs
LOAD DATA LOCAL INFILE 'xml_output/item_rp_orgs.csv'
INTO TABLE item_rp_orgs
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@id, uid, @addr_no, @org_pref, @ROR_ID, @org_id, @organization)
SET
    addr_no = NULLIF(@addr_no, ''),
    org_pref = NULLIF(@org_pref, ''),
    ROR_ID = NULLIF(@ROR_ID, ''),
    org_id = NULLIF(@org_id, ''),
    organization = NULLIF(@organization, '');

-- Import item_rp_suborgs
LOAD DATA LOCAL INFILE 'xml_output/item_rp_suborgs.csv'
INTO TABLE item_rp_suborgs
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@id, uid, @addr_no, @suborganization)
SET
    addr_no = NULLIF(@addr_no, ''),
    suborganization = NULLIF(@suborganization, '');

-- Import item_contributors
LOAD DATA LOCAL INFILE 'xml_output/item_contributors.csv'
INTO TABLE item_contributors
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@id, uid, @seq_no, @orcid_id, @r_id, @r_id_role, @display_name, @full_name, @first_name, @last_name)
SET
    seq_no = NULLIF(@seq_no, ''),
    orcid_id = NULLIF(@orcid_id, ''),
    r_id = NULLIF(@r_id, ''),
    r_id_role = NULLIF(@r_id_role, ''),
    display_name = NULLIF(@display_name, ''),
    full_name = NULLIF(@full_name, ''),
    first_name = NULLIF(@first_name, ''),
    last_name = NULLIF(@last_name, '');

-- =============================================================================
-- Section 3: Category Information Tables (2 tables)
-- =============================================================================

-- Import item_headings
LOAD DATA LOCAL INFILE 'xml_output/item_headings.csv'
INTO TABLE item_headings
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(uid, @headings)
SET headings = NULLIF(@headings, '');

-- Import item_subjects
LOAD DATA LOCAL INFILE 'xml_output/item_subjects.csv'
INTO TABLE item_subjects
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(uid, @subject, @ascatype)
SET
    subject = NULLIF(@subject, ''),
    ascatype = NULLIF(@ascatype, '');

-- =============================================================================
-- Section 4: References Tables (2 tables)
-- =============================================================================

-- Import item_references
LOAD DATA LOCAL INFILE 'xml_output/item_references.csv'
INTO TABLE item_references
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
ESCAPED BY ''
LINES TERMINATED BY '\r\n'  -- 关键：使用 Windows 行尾
IGNORE 1 LINES
(uid, @occurence_order, @cited_uid, @cited_author, @cited_year, @cited_page, 
 @cited_volume, @cited_title, @cited_work, @cited_doi, @cited_assignee, @patent_no)
SET
    occurence_order = NULLIF(@occurence_order, ''),
    cited_uid = NULLIF(@cited_uid, ''),
    cited_author = NULLIF(@cited_author, ''),
    cited_year = NULLIF(@cited_year, ''),
    cited_page = NULLIF(@cited_page, ''),
    cited_volume = NULLIF(@cited_volume, ''),
    cited_title = NULLIF(@cited_title, ''),
    cited_work = NULLIF(@cited_work, ''),
    cited_doi = NULLIF(@cited_doi, ''),
    cited_assignee = NULLIF(@cited_assignee, ''),
    patent_no = NULLIF(@patent_no, '');

-- Import item_cite_locations
LOAD DATA LOCAL INFILE 'xml_output/item_cite_locations.csv'
INTO TABLE item_cite_locations
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
ESCAPED BY ''
LINES TERMINATED BY '\r\n'  -- 关键：使用 Windows 行尾
IGNORE 1 LINES
(uid, @occurence_order, @physical_location, @section, @function)
SET
    occurence_order = NULLIF(@occurence_order, ''),
    physical_location = NULLIF(@physical_location, ''),
    section = NULLIF(@section, ''),
    function = NULLIF(@function, '');

-- =============================================================================
-- Section 5: Funding Information Tables (2 tables)
-- =============================================================================

-- Import item_acks
LOAD DATA LOCAL INFILE 'xml_output/item_acks.csv'
INTO TABLE item_acks
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
ESCAPED BY ''
LINES TERMINATED BY '\r\n'  -- 关键：使用 Windows 行尾
IGNORE 1 LINES
(uid, @ack_text)
SET ack_text = NULLIF(@ack_text, '');

-- Import item_grants
LOAD DATA LOCAL INFILE 'xml_output/item_grants.csv'
INTO TABLE item_grants
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
ESCAPED BY ''
LINES TERMINATED BY '\r\n'  -- 关键：使用 Windows 行尾
IGNORE 1 LINES
(uid, @grant_agency, @grant_agency_pref, @grant_id, @grant_source)
SET
    grant_agency = NULLIF(@grant_agency, ''),
    grant_agency_pref = NULLIF(@grant_agency_pref, ''),
    grant_id = NULLIF(@grant_id, ''),
    grant_source = NULLIF(@grant_source, '');

-- =============================================================================
-- Section 6: Conference Information Table (1 table)
-- =============================================================================

-- Import item_conferences
LOAD DATA LOCAL INFILE 'xml_output/item_conferences.csv'
INTO TABLE item_conferences
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
ESCAPED BY ''
LINES TERMINATED BY '\r\n'  -- 关键：使用 Windows 行尾
IGNORE 1 LINES
(uid, @conf_id, @conf_info, @conf_title, @conf_start, @conf_end, 
 @conf_date, @conf_city, @conf_state, @sponsor)
SET
    conf_id = NULLIF(@conf_id, ''),
    conf_info = NULLIF(@conf_info, ''),
    conf_title = NULLIF(@conf_title, ''),
    conf_start = NULLIF(@conf_start, ''),
    conf_end = NULLIF(@conf_end, ''),
    conf_date = NULLIF(@conf_date, ''),
    conf_city = NULLIF(@conf_city, ''),
    conf_state = NULLIF(@conf_state, ''),
    sponsor = NULLIF(@sponsor, '');

-- Re-enable foreign key checks
SET FOREIGN_KEY_CHECKS = 1;

-- =============================================================================
-- End of CSV import
-- =============================================================================
